"""
observer/code_writer_agent.py
------------------------------
CodeWriterAgent — The Self-Documenting Observer

Role in the System
------------------
The CodeWriterAgent is NOT a pipeline step.
It is a PASSIVE OBSERVER that watches every agent execute and
incrementally builds a fully reproducible Python script from the
exact code that actually ran.

How it works
------------
1.  After every pipeline step completes, the orchestrator calls:
        code_writer.observe(result)

2.  CodeWriterAgent extracts:
        - result["code_equivalent"]   → the actual LLM-generated code
        - result["step_name"]         → which step it belongs to
        - result["reasoning"]         → LLM's explanation of why it chose this approach
        - result["agent_name"]        → which agent ran it
        - result["elapsed_ms"]        → how long it took
        - result["status"]            → success / failed

3.  It then:
        a. Parses all import statements out of the code snippet
        b. Deduplicates imports across all steps (no double-imports)
        c. Writes a header block (pipeline metadata)
        d. Appends the step code under a clearly labelled section
        e. Appends a footer with metrics after the last step

4.  The output file (generated_code/pipeline_script.py) is a
    COMPLETE, RUNNABLE Python script that reproduces the entire
    pipeline from scratch on new data.

Output file structure
---------------------
    # ═══════════════════════════════════════════════════
    # AUTO-GENERATED PIPELINE SCRIPT
    # Generated by: Agentic Pipeline Builder
    # Pipeline ID : abc12345
    # Steps       : load_dataset → normalize → train_model
    # ═══════════════════════════════════════════════════

    # ── IMPORTS (deduplicated across all steps) ──────
    import pandas as pd
    import numpy as np
    from sklearn.preprocessing import StandardScaler
    ...

    # ══════════════════════════════════════════════════
    # STEP 1: load_dataset
    # Agent   : DynamicAgent[load_dataset]
    # Duration: 1243.2 ms
    # Reasoning: "I chose pd.read_csv because the schema..."
    # ══════════════════════════════════════════════════
    df = pd.read_csv("data/sample_data.csv")
    ...

    # ── PIPELINE EXECUTION SUMMARY ───────────────────
    # Total steps  : 6
    # Successful   : 6
    # Total time   : 18.4 s
    # ─────────────────────────────────────────────────
"""

from __future__ import annotations

import re
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

from utils.logger import PipelineLogger


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_OUTPUT_DIR  = Path("generated_code")
_SCRIPT_PATH = _OUTPUT_DIR / "pipeline_script.py"


# ---------------------------------------------------------------------------
# Import parser
# ---------------------------------------------------------------------------

class _ImportParser:
    """
    Extracts, normalises, and deduplicates Python import statements
    from code snippets.

    Handles
    -------
    - `import X`
    - `import X as Y`
    - `from X import Y`
    - `from X import Y, Z`
    - `from X import (Y, Z)`
    - Multi-line imports

    Normalisation
    -------------
    Each import is stored as a canonical string so that
    `from sklearn.preprocessing import StandardScaler` added twice
    only appears once in the output.
    """

    def __init__(self) -> None:
        # Set of canonical import lines already seen
        self._seen: Set[str] = set()
        # Ordered list (insertion order preserved via dict trick)
        self._ordered: List[str] = []

    def add_from_code(self, code: str) -> List[str]:
        """
        Parse all import statements from a code string.
        Returns the list of NEW imports (not seen before).
        """
        new_imports: List[str] = []

        # Extract import lines using regex (handles most real-world cases)
        # Pattern covers:  import X / from X import Y / from X import (...)
        pattern = re.compile(
            r"^(?:from\s+\S+\s+import\s+.+|import\s+.+)",
            re.MULTILINE,
        )
        for match in pattern.finditer(code):
            raw = match.group(0).strip()
            # Normalise: collapse whitespace
            normalised = re.sub(r"\s+", " ", raw)
            if normalised not in self._seen:
                self._seen.add(normalised)
                self._ordered.append(normalised)
                new_imports.append(normalised)

        return new_imports

    def get_all(self) -> List[str]:
        """Return all unique import lines in insertion order."""
        return list(self._ordered)

    def clear(self) -> None:
        """Reset for a new pipeline run."""
        self._seen.clear()
        self._ordered.clear()


# ---------------------------------------------------------------------------
# Step record
# ---------------------------------------------------------------------------

class _StepRecord:
    """Holds everything about one completed pipeline step."""

    def __init__(
        self,
        step_index:     int,
        step_name:      str,
        agent_name:     str,
        code:           str,
        reasoning:      str,
        status:         str,
        elapsed_ms:     float,
        input_summary:  str,
        output_summary: str,
        timestamp:      str,
    ) -> None:
        self.step_index     = step_index
        self.step_name      = step_name
        self.agent_name     = agent_name
        self.code           = code
        self.reasoning      = reasoning
        self.status         = status
        self.elapsed_ms     = elapsed_ms
        self.input_summary  = input_summary
        self.output_summary = output_summary
        self.timestamp      = timestamp

    @classmethod
    def from_result(cls, step_index: int, result: Dict[str, Any]) -> "_StepRecord":
        return cls(
            step_index     = step_index,
            step_name      = result.get("step_name",      "unknown"),
            agent_name     = result.get("agent_name",     "unknown"),
            code           = result.get("code_equivalent",""),
            reasoning      = result.get("reasoning",      ""),
            status         = result.get("status",         "unknown"),
            elapsed_ms     = result.get("elapsed_ms",     0.0),
            input_summary  = result.get("input_summary",  ""),
            output_summary = result.get("output_summary", ""),
            timestamp      = result.get("timestamp",      ""),
        )


# ---------------------------------------------------------------------------
# CodeWriterAgent
# ---------------------------------------------------------------------------

class CodeWriterAgent:
    """
    Incrementally builds pipeline_script.py from LLM-generated code.

    Usage
    -----
    .. code-block:: python

        writer = CodeWriterAgent(pipeline_id="abc123", pipeline_steps=steps)
        writer.init_script()

        # After each agent completes:
        writer.observe(result_dict)

        # After the whole pipeline:
        writer.finalise(elapsed_s=12.3, success=True)

    The resulting file at  generated_code/pipeline_script.py
    is a complete, runnable Python script.
    """

    def __init__(
        self,
        pipeline_id:    str,
        pipeline_steps: List[str],
    ) -> None:
        self.pipeline_id    = pipeline_id
        self.pipeline_steps = pipeline_steps
        self._logger        = PipelineLogger("observer.CodeWriterAgent")
        self._import_parser = _ImportParser()
        self._step_records: List[_StepRecord] = []
        self._step_counter  = 0
        self._start_time    = time.time()

        # Ensure output directory exists
        _OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def init_script(self) -> None:
        """
        Write the file header to pipeline_script.py.
        Called ONCE at the start of the pipeline run.
        Clears any previous content.
        """
        self._import_parser.clear()
        self._step_records.clear()
        self._step_counter = 0
        self._start_time   = time.time()

        header = self._build_file_header()

        with _SCRIPT_PATH.open("w", encoding="utf-8") as f:
            f.write(header)

        self._logger.info(
            f"pipeline_script.py initialised → {_SCRIPT_PATH}"
        )

    def observe(self, result: Dict[str, Any]) -> None:
        """
        Process one agent result and append its code to the script.

        Parameters
        ----------
        result:
            The dict returned by DynamicAgent.execute().
            Must contain: step_name, code_equivalent, reasoning,
            agent_name, elapsed_ms, status.
        """
        self._step_counter += 1
        record = _StepRecord.from_result(self._step_counter, result)
        self._step_records.append(record)

        step_name = record.step_name
        status    = record.status
        code      = record.code.strip()

        self._logger.info(
            f"Observing step {self._step_counter}: '{step_name}' "
            f"[{status.upper()}]"
        )

        # ── Handle failed steps ───────────────────────────────────────
        if status != "success" or not code:
            self._append_failed_step_block(record)
            self._logger.warning(
                f"Step '{step_name}' failed — writing error placeholder"
            )
            return

        # ── Parse and register new imports ────────────────────────────
        new_imports = self._import_parser.add_from_code(code)
        if new_imports:
            self._update_imports_block()
            self._logger.debug(
                f"New imports from '{step_name}': {new_imports}"
            )

        # ── Strip imports from the body code ─────────────────────────
        body_code = self._strip_imports(code)

        # ── Append the step block ─────────────────────────────────────
        self._append_step_block(record, body_code)

        lines_written = len(body_code.splitlines())
        self._logger.code_written(step_name, lines_written)

    def finalise(
        self,
        elapsed_s: float,
        success:   bool,
    ) -> None:
        """
        Append the execution summary footer to the script.
        Called ONCE after the full pipeline completes or fails.

        Parameters
        ----------
        elapsed_s:
            Total wall-clock seconds the pipeline took.
        success:
            Whether the pipeline completed without fatal error.
        """
        footer = self._build_footer(elapsed_s, success)

        with _SCRIPT_PATH.open("a", encoding="utf-8") as f:
            f.write(footer)

        self._logger.info(
            f"pipeline_script.py finalised — "
            f"{self._step_counter} step(s) | "
            f"{'SUCCESS' if success else 'PARTIAL'} | "
            f"{elapsed_s:.2f}s"
        )
        self._logger.info(f"Script saved → {_SCRIPT_PATH.resolve()}")

    def get_script_path(self) -> Path:
        """Return the path to the generated script file."""
        return _SCRIPT_PATH

    def get_script_content(self) -> str:
        """Return the current content of the generated script."""
        if _SCRIPT_PATH.exists():
            return _SCRIPT_PATH.read_text(encoding="utf-8")
        return ""

    def print_script(self) -> None:
        """Print the current script content to stdout."""
        content = self.get_script_content()
        print("\n" + "=" * 70)
        print("  GENERATED PIPELINE SCRIPT")
        print("=" * 70)
        print(content)
        print("=" * 70 + "\n")

    # ------------------------------------------------------------------
    # Private builders
    # ------------------------------------------------------------------

    def _build_file_header(self) -> str:
        """Build the file header comment block."""
        now        = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        steps_str  = " -> ".join(self.pipeline_steps)
        n_steps    = len(self.pipeline_steps)

        return (
            '"""\n'
            "AUTO-GENERATED PIPELINE SCRIPT\n"
            "================================\n"
            "Generated by : Agentic Pipeline Builder System\n"
            f"Pipeline ID  : {self.pipeline_id}\n"
            f"Generated at : {now}\n"
            f"Steps ({n_steps})  : {steps_str}\n"
            "\n"
            "WARNING: This file is auto-generated.\n"
            "All code below was written by an LLM (gpt-oss:120b-cloud via Ollama)\n"
            "based on live inspection of the actual DataFrame at each step.\n"
            '"""\n'
            "\n"
            "# ── IMPORTS ──────────────────────────────────────────────────────\n"
            "# (deduplicated across all pipeline steps)\n"
            "# [imports will be injected here as steps are observed]\n"
            "\n"
            f"_PIPELINE_ID = '{self.pipeline_id}'\n"
            "\n\n"
        )

    def _update_imports_block(self) -> None:
        """
        Re-write the imports section at the top of the file.

        Because imports can arrive from any step, we maintain a
        placeholder comment and replace the section between it and
        the first non-import line whenever new imports arrive.
        """
        current = _SCRIPT_PATH.read_text(encoding="utf-8")

        # Build the new imports block
        imports_block = (
            "# ── IMPORTS ──────────────────────────────────────────────────────\n"
            "# (deduplicated across all pipeline steps)\n"
        )
        for imp in self._import_parser.get_all():
            imports_block += imp + "\n"
        imports_block += "\n"

        # Replace the existing imports section
        # Pattern: from the IMPORTS header to the _PIPELINE_ID line
        pattern = re.compile(
            r"# ── IMPORTS ─+\n.*?(?=\n_PIPELINE_ID)",
            re.DOTALL,
        )
        new_content = pattern.sub(imports_block.rstrip("\n"), current)

        with _SCRIPT_PATH.open("w", encoding="utf-8") as f:
            f.write(new_content)

    def _append_step_block(
        self,
        record:    _StepRecord,
        body_code: str,
    ) -> None:
        """Append a fully annotated step block to the script."""
        divider   = "═" * 66
        elapsed_s = record.elapsed_ms / 1000

        # Wrap reasoning to 70 chars
        reasoning_wrapped = self._wrap_comment(record.reasoning, width=66)

        block = (
            f"\n\n# {divider}\n"
            f"# STEP {record.step_index}: {record.step_name.upper()}\n"
            f"# {divider}\n"
            f"# Agent     : {record.agent_name}\n"
            f"# Status    : {record.status.upper()}\n"
            f"# Duration  : {elapsed_s:.3f}s\n"
            f"# Timestamp : {record.timestamp}\n"
            f"# Input     : {record.input_summary}\n"
            f"# Output    : {record.output_summary}\n"
            f"#\n"
            f"# LLM Reasoning:\n"
            f"{reasoning_wrapped}\n"
            f"# {divider}\n"
            f"\n"
            f"{body_code}\n"
        )

        with _SCRIPT_PATH.open("a", encoding="utf-8") as f:
            f.write(block)

    def _append_failed_step_block(self, record: _StepRecord) -> None:
        """Append a placeholder block for a failed step."""
        divider = "─" * 66
        block = (
            f"\n\n# {divider}\n"
            f"# STEP {record.step_index}: {record.step_name.upper()} [FAILED]\n"
            f"# {divider}\n"
            f"# Agent    : {record.agent_name}\n"
            f"# Status   : FAILED\n"
            f"# Duration : {record.elapsed_ms/1000:.3f}s\n"
            f"#\n"
            f"# This step failed. No code was executed.\n"
            f"# Re-run the pipeline to regenerate.\n"
            f"# {divider}\n"
            f"\n"
            f"# raise RuntimeError('Step {record.step_name!r} failed during pipeline run')\n"
        )

        with _SCRIPT_PATH.open("a", encoding="utf-8") as f:
            f.write(block)

    def _build_footer(self, elapsed_s: float, success: bool) -> str:
        """Build the execution summary footer."""
        total_steps = len(self._step_records)
        success_ct  = sum(1 for r in self._step_records if r.status == "success")
        failed_ct   = total_steps - success_ct
        status_str  = "COMPLETED SUCCESSFULLY" if success else "COMPLETED WITH ERRORS"
        now         = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

        step_summary_lines = ""
        for rec in self._step_records:
            icon = "✔" if rec.status == "success" else "✘"
            step_summary_lines += (
                f"#   {icon}  {rec.step_index}. {rec.step_name:<35} "
                f"{rec.elapsed_ms/1000:.3f}s\n"
            )

        # ── Model & data saving code ──────────────────────────────────
        save_code = (
            "\n\n"
            "# ════════════════════════════════════════════════════════════════\n"
            "# SAVE OUTPUTS\n"
            "# ════════════════════════════════════════════════════════════════\n"
            "\n"
            "import os\n"
            "os.makedirs('outputs', exist_ok=True)\n"
            "\n"
            "# Save cleaned dataset\n"
            "df.to_csv('outputs/cleaned_data.csv', index=False, encoding='utf-8')\n"
            "print(f'Cleaned data saved -> outputs/cleaned_data.csv ({df.shape[0]} rows x {df.shape[1]} cols)')\n"
            "\n"
            "# Save trained model\n"
            "import joblib\n"
            "if 'trained_model' in dir():\n"
            "    joblib.dump(trained_model, 'outputs/model.pkl')\n"
            "    print(f'Model saved -> outputs/model.pkl ({type(trained_model).__name__})')\n"
            "elif 'trained_models' in dir() and isinstance(trained_models, dict):\n"
            "    # Save best model (first in dict) and all models\n"
            "    best_name, best_model = next(iter(trained_models.items()))\n"
            "    joblib.dump(best_model, 'outputs/model.pkl')\n"
            "    print(f'Best model saved -> outputs/model.pkl ({best_name}: {type(best_model).__name__})')\n"
            "    # Save all models\n"
            "    for name, model in trained_models.items():\n"
            "        joblib.dump(model, f'outputs/model_{name}.pkl')\n"
            "    print(f'All {len(trained_models)} models saved to outputs/')\n"
            "else:\n"
            "    print('WARNING: No trained model found to save')\n"
            "\n"
            "print('All outputs saved to outputs/ directory')\n"
        )

        summary_block = (
            "\n\n"
            "# ════════════════════════════════════════════════════════════════\n"
            f"# PIPELINE EXECUTION SUMMARY — {status_str}\n"
            "# ════════════════════════════════════════════════════════════════\n"
            f"# Completed at  : {now}\n"
            f"# Total steps   : {total_steps}\n"
            f"# Successful    : {success_ct}\n"
            f"# Failed        : {failed_ct}\n"
            f"# Total time    : {elapsed_s:.3f}s\n"
            "#\n"
            "# Step breakdown:\n"
            f"{step_summary_lines}"
            "# ════════════════════════════════════════════════════════════════\n"
        )

        return save_code + summary_block

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _strip_imports(code: str) -> str:
        """
        Remove all import statements from a code snippet.
        Returns the non-import lines with leading blank lines stripped.
        """
        lines     = code.splitlines()
        body_lines = []
        for line in lines:
            stripped = line.strip()
            # Skip import lines (they go into the consolidated imports block)
            if re.match(r"^(?:import\s+|from\s+\S+\s+import\s+)", stripped):
                continue
            body_lines.append(line)

        # Strip leading blank lines
        while body_lines and not body_lines[0].strip():
            body_lines.pop(0)

        return "\n".join(body_lines)

    @staticmethod
    def _wrap_comment(text: str, width: int = 66) -> str:
        """
        Wrap a long string into commented lines of max `width` chars.
        Each line is prefixed with '#   '.
        """
        if not text:
            return "#   (no reasoning provided)"
        words    = text.split()
        lines    = []
        cur_line = "#   "
        for word in words:
            if len(cur_line) + len(word) + 1 > width:
                lines.append(cur_line.rstrip())
                cur_line = "#   " + word + " "
            else:
                cur_line += word + " "
        if cur_line.strip() != "#":
            lines.append(cur_line.rstrip())
        return "\n".join(lines)